apiVersion: v1
kind: Service
metadata:
  name: react-hello-world-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: react-hello-world
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000